### ISSUE TITLE
Discussion About the Slug Problem

### ISSUE THREAD

**Issue by abdulrcs** [renatorib/github-blog#19]
Hi @renatorib 

I was just wondering about the slug problem.

I agree that it's not scalable because GitHub labels is limited to 50 characters.

![image](https://github.com/renatorib/github-blog/assets/54136956/459ad5de-0201-4be4-9e4a-81b14b095d88)

You mentioned _"It's impossible to create a safe and unique slug for your posts."_ in the readme, but by doing this query for example:
```js
  const data = await blog.getPost({
    query: {
      author: 'abdulrcs',
      search: 'how-i-make-my-first-real-open-source-contribution',
    },
  })
```
![image](https://github.com/renatorib/github-blog/assets/54136956/c59f4df0-1ec2-4fca-8212-29f697a04de4)

It queries `search` that matches a text in the issue body right, _so it is possible_ to make a unique identifier to query for post without using labels, and it's safe because I identified the author name.

Why isn't that the default way of querying for the slug, am I missing something here? any thoughts?

Also, huge thanks for building this API, It really motivates me to continue writing again since the friction of writing a GitHub issue is less daunting than using a fully-fledged CMS.

**Comment by renatorib** [comment]
Hello @abdulrcs 
Thank you for caring about the problem!

Although this solution works with big slugs, in many scenarios this would be problematic.
Imagine a post where the slug is just `react`. It would match a lot of other posts/issues that includes react.

Since I cannot query issues with the `exact` string, it can also collides similar slugs.
Imagine a post with `slug-foo` and `slug-foo-bar`. If I query for `slug-foo` it will match both and there's no guarantee of the order. It will depends on its engagement.

That's what I meant when I say _"It's impossible to create a safe and unique slug for your posts."_
There's no **reliable** way other than with labels

**Comment by abdulrcs** [comment]
> Imagine a post with slug-foo and another with slug-foo-bar. If I query for slug-foo it will match both and there's no guarantee of the order. The slug-foo-bar one can appear first. It will depends on its engagement.

I see, I'll keep this in mind for my use case, thanks for the explanation @renatorib!
