### ISSUE TITLE
Overnight breaking changes?

### ISSUE THREAD

**Issue by selfagency** [renatorib/github-blog#3]
I've been building a project using this for the last couple of days and it's been working great — so thanks for that. But suddenly today, my posts are coming back `null`. So I checked out the GraphQL response the Github API is sending back from your call, and it appears that

```
edges: [
  cursor: "etc.",
  post: { etc. }
]
```

is returning as

```
edges: [
  cursor: "etc.",
  node: { etc. }
]
```

There have been no public updates about it changing, so I don't know if that's the case or something else is happening that I'm not catching. The post content is present in the GraphQL response, but after I run `blog.getPosts()` the post object itself returns as `null`.

Thanks again.

**Comment by renatorib** [comment]
What version are you using?

**Comment by selfagency** [comment]
@renatorib The one prior to your latest commit.

**Comment by renatorib** [comment]
Sorry for disappearing, this project was out of my priorities and I forgot to reply here.

The entire purpose of github-blog is mapping issue-related types to post-related types.
Without github-blog you can get the same result just by calling the github api... but then you will get issues not posts, you will get labels, not tags, etc. So that's why I mapped it to `post` instead of `node` (although I think it would be fine if I called node too).

So that's why github responds with node and github-blog returns as post. See the code here https://github.com/renatorib/github-blog/blob/master/src/methods/getPosts.ts#L58

Also, it's the same api since first commit, as you can see here https://github.com/renatorib/github-blog/commit/a528a8b92e7006c55d0efa9e74200f0c39f2a770#diff-2ce5bebbc692f4713ff306203c1825b5e7d0197376a5cb2e175bca7f93b35256R52

The api never changed, so, it's weird it breaked your project.  
Maybe something else broke it and you mistakenly thought it might have been that?

Btw, I haven't continued the project yet, although it's still on my radar
